---
- name: install docker
  hosts: all
  become: true
  tasks:
   - name: copy the script
     copy:
      src: scripts/docker.sh
      dest: /home/ubuntu
      mode: 0777
   - name: run the script
     shell: /home/ubuntu/docker.sh
